chore: remove unused config items
eqlabs/pathfinder pull request #1555
Opened 2023-11-22 09:28 UTC by pierre-l

Get rid of `--poll-pending` and `--python-subprocesses`.
Remove the associated `pending` module.
Delete the `py` dir section from `contributing.md`

Closes #1548

2023-11-22 10:45 UTC, Mirko-von-Leipzig commented on crates/pathfinder/src/state/sync/l2.rs
> -                    }
Ah I should have been more specific. The pending polling itself should remain - it just shouldn't be configurable from outside. Should just always be 2s set from main.

2023-11-22 10:45 UTC, Mirko-von-Leipzig commented on CHANGELOG.md
> +- `--poll-pending` and `--python-subprocesses` command line options
```suggestion
- `--poll-pending` configuration option. This is now always enabled and set to 2s.
- `--python-subprocesses` configuration option. This is superceded by `--rpc.execution-concurrency`.
```

2023-11-22 13:51 UTC, Mirko-von-Leipzig commented
Also check the readme for any mentions of these flags

2023-11-24 09:36 UTC, Mirko-von-Leipzig approved these changes
LGTM. On a side note, its generally bad to hardcode poll durations because it makes testing difficult. In this case I'm fine with it though because the sync code is already impossible to test properly and a rework soonish will decouple things like this.

2023-11-24 09:43 UTC, CHr15F0x commented on crates/pathfinder/src/state/sync/l2.rs
> +                    const PENDING_POLL_INTERVAL: std::time::Duration =
Poll pending is unsupported in p2p, so we should just sleep here for 2 secs if feature="p2p".

2023-11-24 09:44 UTC, CHr15F0x requested changes
Just that one comment of mine and we're good :+1: .

2023-11-24 14:56 UTC, CHr15F0x approved these changes

2023-11-24 15:00 UTC, kkovaacs approved these changes

2023-11-27 09:29 UTC, merged